from __future__ import annotations

SKILLS = sorted(
    {
        "python",
        "java",
        "c++",
        "javascript",
        "typescript",
        "react",
        "node",
        "express",
        "fastapi",
        "django",
        "flask",
        "sql",
        "postgresql",
        "mysql",
        "mongodb",
        "redis",
        "docker",
        "kubernetes",
        "aws",
        "azure",
        "gcp",
        "linux",
        "git",
        "github",
        "ci/cd",
        "ml",
        "machine learning",
        "deep learning",
        "nlp",
        "computer vision",
        "pandas",
        "numpy",
        "scikit-learn",
        "tensorflow",
        "pytorch",
        "transformers",
        "bert",
        "spacy",
        "tf-idf",
        "rest",
        "api",
        "microservices",
        "data science",
        "statistics",
        "power bi",
        "tableau",
    }
)
